Update merge_scheduler.yml

diff --git a/.github/workflows/merge_scheduler.yml b/.github/workflows/merge_scheduler.yml
--- a/.github/workflows/merge_scheduler.yml
+++ b/.github/workflows/merge_scheduler.yml
@@ -40,8 +40,12 @@ jobs:
                     echo "No open pull requests were found"
                     exit 1
                 else
+                    echo "*************************************************"
+                    echo "*************************************************"
                     echo "**** The following open pull request were found: "
                     cat $OPEN_PR_FILE
+                    echo "*************************************************"
+                    echo "*************************************************"
                 fi
 
             - name: Get list of approved pr with matching trigger_phrase
@@ -64,8 +68,12 @@ jobs:
                     echo "No matching pull request found. Exiting..."
                     exit 1
                 else
+                    echo "*************************************************"
+                    echo "*************************************************"
                     echo "***** THe following pull request were matched: "
                     cat $MATCHED_PR_FILE
+                    echo "*************************************************"
+                    echo "*************************************************"
                 fi
 
             - name: Get list of pr with all checks passed
@@ -100,8 +108,12 @@ jobs:
                     echo "***** No pull request passed all checks. Exiting..."
                     exit 1
                 else
+                    echo "*************************************************"
+                    echo "*************************************************"
                     echo "***** The following pull request passed all checks: "
                     cat $PASSED_PR_FILE
+                    echo "*************************************************"
+                    echo "*************************************************"
                 fi
 
             - name: merge passing pull requests
@@ -113,15 +125,16 @@ jobs:
 
                     set +e
                     echo "Attempting to merge pull request #$pr_number....."
-                    gh pr merge $pr_number --repo $TARGET_REPO --merge || echo "Skipping to next pr due to merge failure"
+                    gh pr merge $pr_number --repo $TARGET_REPO  --body "mergedBy $TRIGGER_PHRASE" --merge || echo "Skipping to next pr due to merge failure"
                     
+                    # check merge date as a validation that pr is actually merged
+                    merge_validation=$(gh pr view $pr_number --json state | jq -r '.mergedAt')
                     
-                    # checks status to validate that pr is actually merged
-                    pr_status=$(gh pr view $pr_number --json state | jq -r '.state')
-                    echo "PR #$pr_number is $pr_status"
-                    if [ ! -z "$pr_status" ]; then
+                    if [ ! -z "$merge_validation" ]; then
+                        echo "PR #pr_number is successfully merged"
                         echo "PR #$pr_number" >> $MERGED_PR_FILE
                     else
+                        echo "Unable to merge #$pr_number
                         echo "PR #$pr_number" >> $UNMERGED_PR_FILE
                     fi
                     set -e
