Update merge_scheduler.yml

diff --git a/.github/workflows/merge_scheduler.yml b/.github/workflows/merge_scheduler.yml
--- a/.github/workflows/merge_scheduler.yml
+++ b/.github/workflows/merge_scheduler.yml
@@ -129,30 +129,28 @@ jobs:
                     gh pr merge $pr_number -R $TARGET_REPO  --merge || echo "Skipping to next pr due to merge failure"
                     # set -e
 
-                    MERGE_EXIT_CODE=$?
-                    echo $MERGE_EXIT_CODE
+                    # MERGE_EXIT_CODE=$?
+                    # echo $MERGE_EXIT_CODE
 
-                    if [ "$MERGE_EXIT_CODE" == "0" ]; then
-                        echo "Merged pull request #$pr_number successfully."
-                        echo "PR #$pr_number" >> $MERGED_PR_FILE
-                    else
-                        echo "Unable to merge pull request #$pr_number. Exit code: $MERGE_EXIT_CODE"
-                        echo "PR #$pr_number" >> $UNMERGED_PR_FILE                 
-                    fi
-                    
-                    # # check merge date as a validation that pr is actually merged
-                    # merge_validation=$(gh pr view -R $TARGET_REPO $pr_number --json state | jq -r '.mergedAt')
-                    # echo "Merge Status is: $merge_validation"
-                    
-                    # if [ -z "$merge_validation" ]; then
-                    #     echo "Merged pull request #$pr_number"
+                    # if [ "$MERGE_EXIT_CODE" == "0" ]; then
+                    #     echo "Merged pull request #$pr_number successfully."
                     #     echo "PR #$pr_number" >> $MERGED_PR_FILE
+                    # else
+                    #     echo "Unable to merge pull request #$pr_number. Exit code: $MERGE_EXIT_CODE"
+                    #     echo "PR #$pr_number" >> $UNMERGED_PR_FILE                 
                     # fi
                     
-                    # if [ ! -z "$merge_validation" ]; then
-                    #     echo "Unable to merge pull request #$pr_number"
-                    #     echo "PR #$pr_number" >> $UNMERGED_PR_FILE
-                    # fi
+                    # check merge date as a validation that pr is actually merged
+                    merge_validation=$(gh pr view -R $TARGET_REPO $pr_number --json state | jq -r '.mergedAt')
+                    echo "Merge At: $merge_validation"
+                    
+                    if [ -z "$merge_validation" ]; then
+                        echo "Unable to merge pull request #$pr_number"
+                        echo "PR #$pr_number" >> $UNMERGED_PR_FILE
+                    else
+                        echo "Merged pull request #$pr_number successfully"
+                        echo "PR #$pr_number" >> $MERGED_PR_FILE
+                    fi
                     
                     echo ""
                 done < $PASSED_PR_FILE
